# mkdir -p ~/conf && curl -o ~/conf/nps.conf https://raw.githubusercontent.com/djylb/nps/master/conf/nps.conf

services:
  nps:
    image: duan2001/nps
    container_name: nps
    network_mode: "host"
    restart: always
    volumes:
      - ~/conf:/conf
      - /etc/localtime:/etc/localtime:ro
